#cloud-config
ssh_pwauth: true
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${pubkey}
chpasswd:
  list: |
    ${username}:${password}
  expire: false
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - systemctl enable --now qemu-guest-agent
